services:
  db:
    image: postgres:18
    container_name: wiant_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wiant
      POSTGRES_PASSWORD: wiant
      POSTGRES_DB: wiant_db
    ports:
      - "27110:5432"
    volumes:
      - wiant_postgres_data:/var/lib/postgresql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d wiant_db -U wiant"]
        interval: 5s
        timeout: 5s
        retries: 5

  mailpit:
    image: axllent/mailpit:v1.27
    container_name: wiant_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  wiant_postgres_data:
