// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE auth_tokens SET consumed_at = now()
WHERE token_hash = $1 AND purpose = $2 AND consumed_at IS NULL AND expires_at > now()
RETURNING user_id
`

type ConsumeAuthTokenParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.TokenHash, arg.Purpose)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeOAuthAttempt = `-- name: ConsumeOAuthAttempt :one
DELETE FROM oauth_attempts
WHERE state_hash = $1 AND expires_at > now()
RETURNING provider, code_verifier, nonce, intent, user_id, return_to
`

type ConsumeOAuthAttemptRow struct {
	Provider     string
	CodeVerifier pgtype.Text
	Nonce        pgtype.Text
	Intent       string
	UserID       pgtype.Int8
	ReturnTo     string
}

func (q *Queries) ConsumeOAuthAttempt(ctx context.Context, stateHash []byte) (ConsumeOAuthAttemptRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthAttempt, stateHash)
	var i ConsumeOAuthAttemptRow
	err := row.Scan(
		&i.Provider,
		&i.CodeVerifier,
		&i.Nonce,
		&i.Intent,
		&i.UserID,
		&i.ReturnTo,
	)
	return i, err
}

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthTokenParams struct {
	UserID    int64
	Purpose   string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthAttempt = `-- name: CreateOAuthAttempt :exec
INSERT INTO oauth_attempts
    (state_hash, provider, code_verifier, nonce, intent, user_id, return_to, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOAuthAttemptParams struct {
	StateHash    []byte
	Provider     string
	CodeVerifier pgtype.Text
	Nonce        pgtype.Text
	Intent       string
	UserID       pgtype.Int8
	ReturnTo     string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAttempt(ctx context.Context, arg CreateOAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, createOAuthAttempt,
		arg.StateHash,
		arg.Provider,
		arg.CodeVerifier,
		arg.Nonce,
		arg.Intent,
		arg.UserID,
		arg.ReturnTo,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, email_normalized, email_verified_at)
VALUES ($1, $2, now())
RETURNING user_id, email, email_verified_at
`

type CreateOAuthUserParams struct {
	Email           string
	EmailNormalized string
}

type CreateOAuthUserRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (CreateOAuthUserRow, error) {
	row := q.db.QueryRow(ctx, createOAuthUser, arg.Email, arg.EmailNormalized)
	var i CreateOAuthUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_normalized)
VALUES ($1, $2)
RETURNING user_id, email, email_verified_at
`

type CreateUserParams struct {
	Email           string
	EmailNormalized string
}

type CreateUserRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailNormalized)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const findUserIDByEmail = `-- name: FindUserIDByEmail :one
SELECT user_id FROM users WHERE email_normalized = $1
`

func (q *Queries) FindUserIDByEmail(ctx context.Context, emailNormalized string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserIDByEmail, emailNormalized)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.user_id, u.email, u.email_verified_at,
       COALESCE(p.password_hash, '')::text AS password_hash
FROM users u
LEFT JOIN password_credentials p USING (user_id)
WHERE u.email_normalized = $1
`

type GetUserByEmailRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	PasswordHash    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, emailNormalized string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailNormalized)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, email_verified_at
FROM users WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(&i.UserID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const getUserByOAuthIdentity = `-- name: GetUserByOAuthIdentity :one
SELECT u.user_id, u.email, u.email_verified_at
FROM oauth_identities i JOIN users u USING (user_id)
WHERE i.provider = $1 AND i.provider_subject = $2
`

type GetUserByOAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
}

type GetUserByOAuthIdentityRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByOAuthIdentity(ctx context.Context, arg GetUserByOAuthIdentityParams) (GetUserByOAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i GetUserByOAuthIdentityRow
	err := row.Scan(&i.UserID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT u.user_id, u.email, u.email_verified_at
FROM auth_sessions s JOIN users u USING (user_id)
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetUserBySessionRow struct {
	UserID          int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserBySession(ctx context.Context, tokenHash []byte) (GetUserBySessionRow, error) {
	row := q.db.QueryRow(ctx, getUserBySession, tokenHash)
	var i GetUserBySessionRow
	err := row.Scan(&i.UserID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const insertOAuthIdentity = `-- name: InsertOAuthIdentity :exec
INSERT INTO oauth_identities (user_id, provider, provider_subject, provider_email)
VALUES ($1, $2, $3, $4)
`

type InsertOAuthIdentityParams struct {
	UserID          int64
	Provider        string
	ProviderSubject string
	ProviderEmail   pgtype.Text
}

func (q *Queries) InsertOAuthIdentity(ctx context.Context, arg InsertOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, insertOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.ProviderEmail,
	)
	return err
}

const insertPasswordCredential = `-- name: InsertPasswordCredential :exec
INSERT INTO password_credentials (user_id, password_hash) VALUES ($1, $2)
`

type InsertPasswordCredentialParams struct {
	UserID       int64
	PasswordHash string
}

func (q *Queries) InsertPasswordCredential(ctx context.Context, arg InsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, insertPasswordCredential, arg.UserID, arg.PasswordHash)
	return err
}

const invalidateAuthTokens = `-- name: InvalidateAuthTokens :exec
UPDATE auth_tokens SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type InvalidateAuthTokensParams struct {
	UserID  int64
	Purpose string
}

func (q *Queries) InvalidateAuthTokens(ctx context.Context, arg InvalidateAuthTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateAuthTokens, arg.UserID, arg.Purpose)
	return err
}

const listAuthProviders = `-- name: ListAuthProviders :many
SELECT 'password'::text AS provider FROM password_credentials WHERE password_credentials.user_id = $1
UNION ALL
SELECT provider FROM oauth_identities WHERE oauth_identities.user_id = $1
ORDER BY provider
`

func (q *Queries) ListAuthProviders(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuthProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOAuthIdentity = `-- name: TouchOAuthIdentity :exec
UPDATE oauth_identities SET provider_email = $3, updated_at = now()
WHERE provider = $1 AND provider_subject = $2
`

type TouchOAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
	ProviderEmail   pgtype.Text
}

func (q *Queries) TouchOAuthIdentity(ctx context.Context, arg TouchOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, touchOAuthIdentity, arg.Provider, arg.ProviderSubject, arg.ProviderEmail)
	return err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (user_id, password_hash) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET password_hash = excluded.password_hash, updated_at = now()
`

type UpsertPasswordCredentialParams struct {
	UserID       int64
	PasswordHash string
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.UserID, arg.PasswordHash)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE user_id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, userID)
	return err
}
