// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package database

import (
	"context"
)

const getHosts = `-- name: GetHosts :one
SELECT host_id, name FROM hosts
WHERE host_id = $1 LIMIT 1
`

func (q *Queries) GetHosts(ctx context.Context, hostID int64) (Host, error) {
	row := q.db.QueryRow(ctx, getHosts, hostID)
	var i Host
	err := row.Scan(&i.HostID, &i.Name)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT host_id, name FROM hosts
ORDER BY name
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(&i.HostID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
