// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID int64
	Name    string
	HostID  int64
}

type AuthSession struct {
	SessionID int64
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AuthToken struct {
	AuthTokenID int64
	UserID      int64
	Purpose     string
	TokenHash   []byte
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Host struct {
	HostID int64
	Name   string
}

type OauthAttempt struct {
	StateHash    []byte
	Provider     string
	CodeVerifier pgtype.Text
	Nonce        pgtype.Text
	Intent       string
	UserID       pgtype.Int8
	ReturnTo     string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type OauthIdentity struct {
	OauthIdentityID int64
	UserID          int64
	Provider        string
	ProviderSubject string
	ProviderEmail   pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PasswordCredential struct {
	UserID       int64
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	UserID          int64
	Email           string
	EmailNormalized string
	EmailVerifiedAt pgtype.Timestamptz
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
